# Generated by Django 2.2.7 on 2019-11-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': '文件', 'verbose_name_plural': '文件'},
        ),
    ]
