# Generated by Django 2.2.7 on 2019-11-21 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_auto_20191115_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='intro',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000, verbose_name='简介'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='intro',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000, verbose_name='规则'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '正常'), (1, '删除'), (2, '草稿')], default=0, verbose_name='状态'),
        ),
    ]
