# Generated by Django 2.2.7 on 2019-12-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0007_auto_20191221_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='exp',
        ),
        migrations.AddField(
            model_name='rate',
            name='name',
            field=models.CharField(default='校级科研奖项（3分）', max_length=100, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
