# Generated by Django 2.2.7 on 2019-11-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('href', models.URLField(verbose_name='链接')),
                ('intro', models.CharField(max_length=300, verbose_name='简要说明情况')),
                ('status', models.PositiveIntegerField(choices=[(1, '等待'), (0, '解决'), (0, '撤销')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '申诉与举报',
                'verbose_name_plural': '申诉与举报',
            },
        ),
    ]
