# Generated by Django 2.2.7 on 2019-11-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '最新申诉'), (3, '最新消息'), (4, '往年判例')], default=1, verbose_name='展示类型'),
        ),
    ]
