# Generated by Django 2.2.7 on 2019-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20191121_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '最新申诉'), (3, '最近评论'), (4, '往年判例')], default=1, verbose_name='展示类型'),
        ),
    ]
