# Generated by Django 2.2.7 on 2019-11-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='reward',
        ),
    ]
