# Generated by Django 2.2.7 on 2019-12-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.CharField(max_length=100, verbose_name='评论目标'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='target',
            field=models.CharField(max_length=100, verbose_name='评论目标'),
        ),
    ]
