# Generated by Django 2.2.7 on 2019-12-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20191221_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
